name: GuiShop
main: GuiShop\Main
version: 1.0.0-BETA2
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: NicKPlayzYT05
authors: stcraftpev3,IZeaoGamer
description: ShopUI for HypervionPE!
commands:
 shop:
  description: Opens The HypervionPE Shop UI by NicKPlayzYT05
